source 'https://rubygems.org'

gem 'parslet'
gem 'hour-ruby'

group(:development) do
  gem 'pry'
  gem 'guard-rspec'
  gem 'guard-shell'
end

group(:spec) do
  gem 'rspec-core'
  gem 'rspec-expectations'
end
