guard :shell do
  watch(/\.rb$/) do
    system('nvim +UpdateRemotePlugins +q')

    # As of now, plugins cannot be reloaded.
    # Bj√∂rn Linse @bfredl from https://gitter.im/neovim/neovim
    # said he'd hopefuly work on plugin restarting in summer.

    # Dir.glob('/tmp/nvimsocket-*').each do |socket_file|
    #   system <<~EOF
    #     nvr --servername '#{socket_file}' \
    #       --remote-send '<Esc>:so #{ENV['HOME']}/.config/nvim/init.vim<CR>'
    #   EOF
    # end
  end
end

guard :rspec, cmd: 'bundle exec rspec' do
  # watch(%r{^spec/.+_spec\.rb$})
  # watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
  # watch('spec/spec_helper.rb')  { "spec" }
  watch(%r{(spec|lib)/.+\.rb$})
end
